server:
  port: 8082
spring:
  application:
    name: KarateManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5433/karate_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view:
    hibernate:
      ddl-auto: update
    show-sql: true

