package com.karate.management.karatemanagementsystem.domain.user;

public enum KarateClubName {
    LODZKIE_CENTRUM_OKINAWA_SHORIN_RYU_KARATE_I_KOBUDO,
    PIASECZYNSKI_KLUB_OKINAWA_SHORIN_RYU_KARATE,
    WOLOMINSKI_KLUB_SHORIN_RYU_KARATE,
    MIECHOWSKI_KLUB_SHORIN_RYU_KARATE,
    LUBELSKA_AKADEMIA_SPORTU,
    GDANSKI_KLUB_OKINAWA_SHORIN_RYU_KARATE,
    TARNOWSKA_AKADEMIA_KARATE_I_KOBUDO,
    KLUB_OKINAWA_KARATE_DO_WARSZAWA
}
