spring:
  config:
    activate.on-profile: prod

management:
  tracing:
    sampling:
      probability: 0.1   # np. 10% sampling w prod
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.karate: INFO

resilience4j:
  circuitbreaker:
    instances:
      authService:
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
      enrollmentService:
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
      trainingService:
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
      userService:
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
