server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
                - Path=/auth/**
            - id: club-service
              uri: lb://club-service
              predicates:
                - Path=/clubs/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
